name: Simple composite action example
description: "Simple composite action example"

runs:
  using: "composite"
  steps:
    - name: test-composite
      shell: bash
      run: echo "Hello, this is from coposite action workflow"
