name: Simple composite action example
description: "Simple composite action example"

inputs:
  environment_name:
    description: "Name of environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Environment name
      shell: bash
      run: echo "Hello, this is ${{ inputs.environment_name }} environment"
